dpg:
  default:
    perc_var: 0.000000001
    decimal_threshold: 6
    n_jobs: -1
  visualization:
    graph_attrs:
      bgcolor: "white"
      rankdir: "R"
    node_attrs:
      shape: "box"
      fillcolor: "#ffc3c3"
    class_node:
      fillcolor: "#a4c2f4"  # Light blue
      shape: "box"
      style: "rounded, filled"
